storage:
  vector_dbs: "/mnt/vectors/"
  nocow_db_dir: "/mnt/raid/docker/nocow"

  custom:
    qbittorrent_data: "/mnt/media/qbittorrent"

    seafile_media: "/mnt/media/seafile-media"

runtime:
  domain: "datamancy.net"

  admin_email: "admin@datamancy.net"

  admin_user: "sysadmin"

  isolated_docker_vm_host: "gerald@labware.local"
