default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.16.0.0/12
    - 127.0.0.1
    - ::1
  ip_ban_enabled: false
  login_attempts_threshold: 5

frontend:
  themes: !include_dir_merge_named themes

recorder:
  db_url: !env_var HOMEASSISTANT_DB_URL
  auto_purge: true
  purge_keep_days: 30

homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 172.26.0.0/24
        - 172.16.0.0/12
      allow_bypass_login: true

    - type: homeassistant

    - type: command_line
      command: /config/auth_ldap.py
      args: ["--username", "{{ username }}", "--password", "{{ password }}"]
      meta: true

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
