---
title: Datamancy
theme: dark
color: slate
headerStyle: boxed
hideVersion: true
layout:
  AI & Development:
    style: row
    columns: 3
  Collaboration:
    style: row
    columns: 3
  Productivity:
    style: row
    columns: 3
  Social & Media:
    style: row
    columns: 2
  System:
    style: row
    columns: 3
