global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'ntfy'
  routes:
    - match:
        severity: critical
      receiver: 'ntfy-critical'
      continue: true
    - match:
        severity: warning
      receiver: 'ntfy-warning'

receivers:
  - name: 'ntfy'
    webhook_configs:
      - url: 'http://ntfy:80/datamancy-alerts'
        send_resolved: true
        http_config:
          follow_redirects: true
          basic_auth:
            username: ${NTFY_USERNAME}
            password: ${NTFY_PASSWORD}

  - name: 'ntfy-critical'
    webhook_configs:
      - url: 'http://ntfy:80/datamancy-critical'
        send_resolved: true
        http_config:
          follow_redirects: true
          basic_auth:
            username: ${NTFY_USERNAME}
            password: ${NTFY_PASSWORD}

  - name: 'ntfy-warning'
    webhook_configs:
      - url: 'http://ntfy:80/datamancy-warnings'
        send_resolved: true
        http_config:
          follow_redirects: true
          basic_auth:
            username: ${NTFY_USERNAME}
            password: ${NTFY_PASSWORD}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
