apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus.svc.local:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 5s

  - name: Loki
    type: loki
    access: proxy
    url: http://loki.svc.local:3100
    editable: false
    jsonData:
      maxLines: 1000
